name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_NAME }}/frontend-image ./frontend

      - name: Push Frontend Image
        run: |
          docker push ${{ secrets.DOCKER_NAME }}/frontend-image

      - name: Build Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_NAME }}/backend-image ./backend

      - name: Push Backend Image
        run: |
          docker push ${{ secrets.DOCKER_NAME }}/backend-image

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            cd ~/Aws-setup
            sudo docker compose pull
            sudo docker compose up -d